config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    collection do
      get 'top', to: 'restaurants#top'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian),
    message: "%{value} is not a valid cateogry" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restuarants_path
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit() end

  def show() end

  def update
    @restaurant.update(restaurant_params)
    # redirect_to restuarants_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    # redirect_to restuarants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :description, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @review = Review.all
  end

  def create
    @review = Review.create(review_params)
    # redirect_to restuarants_path
  end

  def new
    @review = Review.new
  end

  def edit() end

  def show() end

  def update
    @review.update(review_params)
    # redirect_to restuarants_path(@review)
  end

  def destroy
    @review.destroy
    # redirect_to restuarants_path
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restaurants</title>
</head>
<body>
  <div>
  <h1>All restaurants</h1>
    <% @restaurants.each do |restaurant| %>
        <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
        <p><%= restaurant.description %></p>
        <p><%= restaurant.address %></p>
    <% end %>
  </div>
</body>
</html>

app/views/restaurants/new.html.erb
<%= form_for(@restaurant) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :rating %>
    <%= f.text_field :rating, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<%= link_to "Go back", restaurants_path %>

app/views/restaurants/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @restaurant.name %></title>
</head>
<body>
  <h1><%= @restaurant.name %></h1>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.description %></p>
  <p><%= @restaurant.phone_number %></p>
</body>
</html>